version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  transcriber:
    build:
      context: ./
      dockerfile: ./transcriber/Dockerfile
    container_name: transcriber
    volumes:
      - './transcriber:/src'
    environment:
      - LANG=C.UTF-8
      - PYTHONIOENCODING=utf8
      - LC_ALL=ja_JP.UTF-8
      - ENV=development
      - COMMIT_SHA1=development
      - DB_HOST=db
      - DB_PORT=3306
      - DATABASE_CREATION=create_preset_data
    depends_on:
      - db
    tty: true
