FROM python:3.10-slim

RUN apt update
RUN apt install -y ffmpeg
RUN pip install setuptools-rust
RUN pip install openai-whisper
RUN pip install algoliasearch
RUN pip install SQLAlchemy
RUN pip install psycopg2-binary
